- name: set up "{{ component }}" server
  hosts: "{{ component }}"
  become: yes
  roles:            # this will automatically load a folder called roles in current working directory.
  - "{{ component }}"
